In [1]:
import numpy as np

# DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([
    [1, 2.0, 3],
    [3, 4, 6.5]
])
a3 = np.array(
    [[[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]],
    [[10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]]]
)

In [5]:
a2

array([[1. , 2. , 3. ],
       [3. , 4. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  3.0  4.0  6.5

# 2. Create numpy arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((2, 3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[1, 6, 7, 5, 4],
       [5, 3, 3, 5, 6],
       [4, 2, 7, 1, 4]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.65953675, 0.29028753, 0.93106237],
       [0.99796099, 0.59528498, 0.891731  ],
       [0.17022243, 0.54236536, 0.84184416],
       [0.7650549 , 0.04770079, 0.74012134],
       [0.02036265, 0.94105266, 0.29850849]])

In [27]:
random_array_2.shape

(5, 3)

In [28]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.22242377, 0.18959014, 0.63113816],
       [0.6989174 , 0.8891137 , 0.03908857],
       [0.92145066, 0.31954365, 0.12698004],
       [0.60709097, 0.46194264, 0.33051453],
       [0.0727797 , 0.6260776 , 0.03943023]])

In [29]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [30]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

# 3. Viewing arrays and Matrices

In [31]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [33]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [34]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4 

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [35]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [36]:
#Get the first 4 numbers of the innermost arrays.
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

# 4. Manipulating and Comparing arrays

### Arithmetic

In [37]:
a1

array([1, 2, 3])

In [38]:
ones = np.ones(3)

In [39]:
a1+ones

array([2., 3., 4.])

In [40]:
a2

array([[1. , 2. , 3. ],
       [3. , 4. , 6.5]])

In [41]:
a1 * a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [42]:
# How can you reshape a2 to be compatible with a3?
# Search "How to reshape numpy array"
a2 = np.reshape(a2, (2, 1, 3))

In [43]:
a2 * a3

array([[[  1. ,   4. ,   9. ],
        [  4. ,  10. ,  18. ],
        [  7. ,  16. ,  27. ]],

       [[ 30. ,  44. ,  78. ],
        [ 39. ,  56. ,  97.5],
        [ 48. ,  68. , 117. ]]])

In [44]:
# Floor division removes the decimals( rounds down )
a2 // a1

array([[[1., 1., 1.]],

       [[3., 2., 2.]]])

In [45]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [46]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things.

Use python's methods (`sum()`) on Python datatypes and use Numpy's methods on numpy arrays(`np.sum()`)

In [47]:
# Create a massive python array
massive_array = np.random.random(100000)
massive_array.size

100000

In [48]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [49]:
%timeit sum(massive_array) #Python's sum()
%timeit np.sum(massive_array) # Numpy's sum()

45.8 ms ± 1.85 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
428 µs ± 28.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [50]:
# Standard deviation = a measure of how spread out a group of memebers is from the mean.
np.std(a2)

1.7260262647673315

In [51]:
# Variance = measure of the average degree to which each member is different to the mean.
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

2.9791666666666665

In [52]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2)) 

1.7260262647673315